
#include <map>
#include <algorithm>
#include <cctype>

#include "CScript.h"

static std::map<size_t,command_t> g_scriptCommandNames =
{
    {0,{"label",{ARG_STRING}}},
    {1,{"goto",{ARG_INT}}},
    {2,{"gosub",{}}},
    {3,{"return",{}}},
    {4,{"wait",{ARG_FLT_ID_OR_FLOAT}}},
    {5,{"beep",{}}},
    {6,{"end",{}}},
    {7,{"dim_flt",{ARG_INT}}},
    {8,{"let",{}}},
    {9,{"if",{}}},
    {10,{"rnd",{ARG_INT,ARG_INT}}},
    {11,{"dim_frm",{ARG_INT}}},
    {12,{"dim_act",{ARG_INT}}},
    {13,{"findframe",{ARG_INT,ARG_STRING}}},
    {14,{"frm_seton",{ARG_INT, ARG_INT}}},
    {15,{"frm_ison",{ARG_INT, ARG_INT}}},
    {16,{"frm_linkto",{ARG_INT, ARG_INT}}},
    {17,{"findactor",{ARG_INT, ARG_STRING}}},
    {18,{"call",{ARG_STRING}}},
    {19,{"iffltinrange",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {20,{"playsound",{}}},
    {21,{"playsoundstop",{ARG_INT}}},
    {22,{"playsoundex",{ARG_INT, ARG_INT}}},
    {23,{"stopsound",{ARG_INT}}},
    {24,{"getsoundtime",{}}},
    {25,{"act_setstate",{ARG_INT, ARG_INT}}},
    {26,{"detector_issignal",{ARG_INT, ARG_INT, ARG_INT}}},
    {27,{"detector_setsignal",{ARG_INT, ARG_INT}}},
    {28,{"detector_inrange",{ARG_INT, ARG_INT}}},
    {29,{"setcompass",{ARG_INT}}},
    {30,{"setlmlevel",{ARG_INT, ARG_INT}}},
    {31,{"detector_waitforuse",{ARG_INT}}},
    {32,{"detector_waitforhit",{}}},
    {33,{"commandblock",{ARG_INT}}},
    {34,{"callsubroutine",{ARG_STRING}}},
    {35,{"soundfade",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {36,{"endofmission",{ARG_INT, ARG_INT}}},
    {37,{"program_storage",{}}},
    {38,{"door_lock",{ARG_INT, ARG_INT}}},
    {39,{"door_open",{ARG_INT, ARG_INT}}},
    {40,{"door_enableus",{ARG_INT, ARG_INT}}},
    {41,{"recclear",{}}},
    {42,{"recaddactor",{ARG_INT, ARG_STRING}}},
    {43,{"recload",{ARG_STRING}}},
    {44,{"recloadfull",{ARG_STRING}}},
    {45,{"recwaitforend",{}}},
    {46,{"recunload",{}}},
    {47,{"loadcolltree",{}}},
    {48,{"explosion",{ARG_INT, ARG_INT}}},
    {49,{"timeron",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {50,{"timeroff",{}}},
    {51,{"change_mission",{}}},
    {52,{"camera_setswing",{ARG_INT, ARG_INT, ARG_INT}}},
    {53,{"airplane_start",{ARG_INT, ARG_INT, ARG_INT}}},
    {54,{"airplane_start2",{ARG_INT}}},
    {55,{"debug_text",{ARG_STRING}}},
    {56,{"getactorsdist",{ARG_INT, ARG_INT, ARG_INT}}},
    {57,{"getcardamage",{ARG_INT, ARG_INT}}},
    {58,{"human_addweapon",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {59,{"human_canaddweapon",{ARG_INT, ARG_INT, ARG_INT}}},
    {60,{"human_delweapon",{ARG_INT, ARG_INT}}},
    {61,{"human_isweapon",{ARG_INT, ARG_INT, ARG_INT}}},
    {62,{"human_activateweapon",{ARG_INT, ARG_INT}}},
    {63,{"human_anyweaponinhand",{ARG_INT, ARG_INT}}},
    {64,{"human_anyweaponininventory",{ARG_INT, ARG_INT}}},
    {65,{"human_getiteminrhand",{ARG_INT, ARG_INT}}},
    {66,{"preloadmodel",{}}},
    {67,{"loaddifferences",{}}},
    {68,{"cleardifferences",{}}},
    {69,{"{",{}}},
    {70,{"}",{}}},
    {71,{"setaipriority",{ARG_INT}}},
    {72,{"event",{ARG_INT}}},
    {73,{"setevent",{ARG_INT, ARG_INT, ARG_STRING}}},
    {74,{"event_use_cb",{ARG_INT}}},
    {75,{"enemy_changeanim",{ARG_STRING}}},
    {76,{"human_changeanim",{}}},
    {77,{"dialog_begin",{ARG_INT, ARG_INT}}},
    {78,{"dialog_end",{}}},
    {79,{"dialog_camswitch",{ARG_INT, ARG_INT}}},
    {80,{"game_nightmission",{ARG_INT}}},
    {81,{"human_looktoactor",{ARG_INT, ARG_INT, ARG_INT}}},
    {82,{"human_looktoframe",{}}},
    {83,{"getmissionnumber",{ARG_INT}}},
    {84,{"setmissionnumber",{ARG_INT}}},
    {85,{"human_linktohand",{}}},
    {86,{"human_unlinkfromhand",{ARG_INT}}},
    {87,{"createweaponfromframe",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {88,{"garage_addcar",{ARG_INT}}},
    {89,{"garage_addcaridx",{}}},
    {90,{"garage_delcar",{}}},
    {91,{"garage_generatecars",{}}},
    {92,{"garage_releasecars",{}}},
    {93,{"garage_carmanager",{}}},
    {94,{"player_lockcontrols",{}}},
    {95,{"person_playanim",{}}},
    {96,{"person_stopanim",{}}},
    {97,{"gunshop_menu",{}}},
    {98,{"human_set8slot",{}}},
    {99,{"enemy_forcescript",{}}},
    {100,{"compareownerwithex",{}}},
    {101,{"human_setproperty",{}}},
    {102,{"human_getproperty",{}}},
    {103,{"disablecolls",{}}},
    {104,{"human_getowner",{}}},
    {105,{"human_force_settocar",{}}},
    {106,{"car_setdestroymotor",{}}},
    {107,{"actor_setdir",{}}},
    {108,{"actor_setpos",{}}},
    {109,{"actor_setplacement",{}}},
    {110,{"garage_enablesteal",{}}},
    {111,{"settimeoutevent",{}}},
    {112,{"emitparticle",{}}},
    {113,{"stopparticle",{}}},
    {114,{"setplayerfireevent",{}}},
    {115,{"findnearactor",{}}},
    {116,{"setplayerhornevent",{}}},
    {117,{"human_holster",{}}},
    {118,{"camera_lock",{ARG_INT}}},
    {119,{"camera_unlock",{}}},
    {120,{"setmissionnameid",{}}},
    {121,{"wingman_setindicator",{}}},
    {122,{"wingman_delindicator",{}}},
    {123,{"model_playanim",{ARG_INT, ARG_STRING}}},
    {124,{"model_stopanim",{ARG_INT}}},
    {125,{"model_create",{ARG_INT, ARG_STRING}}},
    {126,{"model_destroy",{ARG_INT}}},
    {127,{"human_changemodel",{ARG_INT, ARG_STRING}}},
    {128,{"autosavegame",{ARG_INT}}},
    {129,{"autosavegamefull",{ARG_INT}}},
    {130,{"human_death",{ARG_INT}}},
    {131,{"human_talk",{ARG_INT, ARG_INT, ARG_INT}}},
    {132,{"human_eraseab",{ARG_INT}}},
    {133,{"human_createab",{ARG_INT}}},
    {134,{"policemanager_on",{ARG_INT, ARG_INT}}},
    {135,{"policemanager_add",{ARG_STRING}}},
    {136,{"policemanager_del",{ARG_STRING}}},
    {137,{"policemanager_setspeed",{}}},
    {138,{"policemanager_forcearrest",{}}},
    {139,{"car_enableus",{}}},
    {140,{"car_setdooropen",{}}},
    {141,{"human_setfiretarget",{}}},
    {142,{"iscarusable",{}}},
    {143,{"door_setopenpose",{}}},
    {144,{"airplane_isdestroyed",{}}},
    {145,{"human_returnfrompanic",{}}},
    {146,{"car_getspeed",{}}},
    {147,{"car_setspeed",{}}},
    {148,{"car_forcestop",{}}},
    {149,{"car_breakmotor",{}}},
    {150,{"inventory_push",{ARG_INT}}},
    {151,{"inventory_pop",{ARG_INT}}},
    {152,{"fuckingbox_add",{ARG_INT, ARG_STRING}}},
    {153,{"fuckingbox_recompile",{}}},
    {154,{"fuckingbox_add_dest",{ARG_INT, ARG_STRING}}},
    {155,{"human_throwitem",{}}},
    {156,{"fuckingbox_getnumbox",{ARG_INT, ARG_INT}}},
    {157,{"fuckingbox_getnumdest",{ARG_INT, ARG_INT}}},
    {158,{"fuckingbox_move",{}}},
    {159,{"wagon_setevent",{ARG_INT, ARG_INT}}},
    {160,{"wagon_getlastnode",{ARG_INT, ARG_INT}}},
    {161,{"car_setspeccoll",{ARG_INT, ARG_INT}}},
    {162,{"car_getspeccoll",{ARG_INT}}},
    {163,{"mission_objectives",{ARG_INT}}},
    {164,{"mission_objectivesremove",{ARG_INT}}},
    {165,{"mission_objectivesclear",{}}},
    {166,{"racing_mission6_init",{}}},
    {167,{"racing_mission6_start",{}}},
    {168,{"car_explosion",{ARG_INT}}},
    {169,{"human_fromcar",{ARG_INT, ARG_INT}}},
    {170,{"",{}}},
    {171,{"car_remove_driver",{ARG_INT}}},
    {172,{"setmodeltocar",{ARG_INT}}},
    {173,{"getenemyaistate",{}}},
    {174,{"get_pm_state",{}}},
    {175,{"get_pm_crashtime",{}}},
    {176,{"get_pm_firetime",{}}},
    {177,{"get_pm_numpredators",{}}},
    {178,{"get_pm_humanstate",{}}},
    {179,{"use_lightcache",{}}},
    {180,{"stream_create",{ARG_INT, ARG_STRING}}},
    {181,{"stream_connect",{}}},
    {182,{"stream_play",{}}},
    {183,{"stream_pause",{}}},
    {184,{"stream_stop",{}}},
    {185,{"stream_destroy",{}}},
    {186,{"stream_fadevol",{}}},
    {187,{"stream_setloop",{}}},
    {188,{"stream_setpos",{}}},
    {189,{"stream_getpos",{}}},
    {190,{"settankhitcount",{}}},
    {191,{"setnoanimhit",{}}},
    {192,{"carlight_main",{}}},
    {193,{"carlight_light",{}}},
    {194,{"carlight_indic_l",{}}},
    {195,{"carlight_indic_r",{}}},
    {196,{"carlight_indic_off",{}}},
    {197,{"car_muststeal",{}}},
    {198,{"car_setprojector",{}}},
    {199,{"garage_cansteal",{}}},
    {200,{"garage_addlaststolen",{}}},
    {201,{"garage_show",{}}},
    {202,{"car_inwater",{}}},
    {203,{"human_forcefall",{}}},
    {204,{"create_physicalobject",{}}},
    {205,{"destroy_physicalobject",{}}},
    {206,{"weather_reset",{}}},
    {207,{"weather_setparam",{}}},
    {208,{"getticktime",{ARG_INT}}},
    {209,{"getgametime",{ARG_INT}}},
    {210,{"getactiveplayer",{}}},
    {211,{"getangleactortoactor",{}}},
    {212,{"setcitytrafficvisible",{}}},
    {213,{"showcardamage",{}}},
    {214,{"character_push",{}}},
    {215,{"character_pop",{}}},
    {216,{"console_addtext",{}}},
    {217,{"camera_setrange",{}}},
    {218,{"actor_duplicate",{}}},
    {219,{"actor_delete",{}}},
    {220,{"human_reset",{}}},
    {221,{"human_havebox",{}}},
    {222,{"human_havebody",{}}},
    {223,{"human_stoptalk",{}}},
    {224,{"enemy_block",{}}},
    {225,{"enemy_unblock",{}}},
    {226,{"get_remote_float",{}}},
    {227,{"get_remote_frame",{}}},
    {228,{"get_remote_actor",{}}},
    {229,{"set_remote_float",{}}},
    {230,{"set_remote_frame",{}}},
    {231,{"set_remote_actor",{}}},
    {232,{"getactorframe",{}}},
    {233,{"zatmyse",{}}},
    {234,{"cardamagevisible",{}}},
    {235,{"",{}}},
    {236,{"",{}}},
    {237,{"ifplayerstealcar",{}}},
    {238,{"intro_subtitle_add",{}}},
    {239,{"subtitle_add",{}}},
    {240,{"math_cos",{}}},
    {241,{"math_sin",{}}},
    {242,{"math_abs",{}}},
    {243,{"frm_getdir",{}}},
    {244,{"frm_setdir",{}}},
    {245,{"frm_getpos",{}}},
    {246,{"frm_setpos",{}}},
    {247,{"frm_getscale",{}}},
    {248,{"frm_setscale",{}}},
    {249,{"frm_getrot",{}}},
    {250,{"frm_setrot",{}}},
    {251,{"frm_getworlddir",{}}},
    {252,{"frm_getworldpos",{}}},
    {253,{"frm_getworldscale",{}}},
    {254,{"frm_getworldrot",{}}},
    {255,{"frm_getlocalmatrix",{}}},
    {256,{"frm_getworldmatrix",{}}},
    {257,{"vect_set",{}}},
    {258,{"vect_copy",{}}},
    {259,{"vect_mul_scl",{}}},
    {260,{"vect_mul_vect",{}}},
    {261,{"vect_mul_quat",{}}},
    {262,{"vect_mul_matrix",{}}},
    {263,{"vect_add_vect",{}}},
    {264,{"vect_sub_vect",{}}},
    {265,{"vect_cross",{}}},
    {266,{"vect_normalize",{}}},
    {267,{"vect_magnitude",{}}},
    {268,{"vect_inverse",{}}},
    {269,{"vect_angleto",{}}},
    {270,{"matrix_zero",{}}},
    {271,{"matrix_identity",{}}},
    {272,{"matrix_copy",{}}},
    {273,{"matrix_inverse",{}}},
    {274,{"matrix_mul",{}}},
    {275,{"quat_copy",{}}},
    {276,{"quat_make",{}}},
    {277,{"quat_setdir",{}}},
    {278,{"quat_extract",{}}},
    {279,{"quat_inverse",{}}},
    {280,{"quat_getrotmatrix",{}}},
    {281,{"quat_add",{}}},
    {282,{"quat_sub",{}}},
    {283,{"quat_mul_scl",{}}},
    {284,{"quat_mul_quat",{}}},
    {285,{"quat_dot",{}}},
    {286,{"quat_normalize",{}}},
    {287,{"quat_rotbymatrix",{}}},
    {288,{"quat_slerp",{}}},
    {289,{"coll_testline",{}}},
    {290,{"vlvp",{}}},
    {291,{"ctrl_read",{ARG_INT,ARG_INT}}},
    {292,{"ctrl_readex",{ARG_INT,ARG_INT}}},
    {293,{"getframefromactor",{}}},
    {294,{"actorupdateplacement",{}}},
    {295,{"racing_autoinvisible",{}}},
    {296,{"setplayerwfallevent",{}}},
    {297,{"car_invisible",{}}},
    {298,{"car_switchshowenergy",{}}},
    {299,{"debug_getframeinfo",{}}},
    {300,{"policeitchforplayer",{}}},
    {301,{"noanimpreload",{}}},
    {302,{"compareactors",{}}},
    {303,{"setnullactor",{}}},
    {304,{"compareframes",{}}},
    {305,{"setnullframe",{}}},
    {306,{"setfreeride",{}}},
    {307,{"enablemap",{}}},
    {308,{"frameistelephone",{}}},
    {309,{"car_calm",{}}},
    {310,{"bridge_shutdown",{}}},
    {311,{"settraffsectorsnd",{}}},
    {312,{"citymusic_off",{}}},
    {313,{"citymusic_on",{}}},
    {314,{"",{}}},
    {315,{"frm_getparent",{}}},
    {316,{"ispointinsector",{}}},
    {317,{"ispointinarea",{}}},
    {318,{"getactivecamera",{}}},
    {319,{"sound_getvolume",{}}},
    {320,{"sound_setvolume",{}}},
    {321,{"racing_change_model",{}}},
    {322,{"citycaching_tick",{}}},
    {323,{"actorlightnesson",{}}},
    {324,{"car_lock",{}}},
    {325,{"car_lock_all",{}}},
    {326,{"pm_showsymbol",{ARG_INT}}},
    {327,{"pm_showprogress",{}}},
    {328,{"pm_setprogress",{}}},
    {329,{"setfilmmusic",{}}},
    {330,{"getfilmmusic",{}}},
    {331,{"human_getseatidx",{}}},
    {332,{"human_entertotruck",{}}},
    {333,{"floatreg_push",{}}},
    {334,{"floatreg_pop",{}}},
    {335,{"airplaneshowdamage",{}}},
    {336,{"setnpckillevent",{}}},
    {337,{"car_getseatcount",{}}},
    {338,{"frm_setalpha",{}}},
    {339,{"human_throwgrenade",{}}},
    {340,{"detector_createdyncoll",{}}},
    {341,{"detector_erasedyncoll",{}}},
    {342,{"car_unbreakable",{}}},
    {343,{"phobj_impuls",{}}},
    {344,{"weather_preparebuffer",{}}},
    {345,{"subtitle",{}}},
    {346,{"human_candie",{}}},
    {347,{"version_is_germany",{}}},
    {348,{"version_is_editor",{}}},
    {349,{"garage_nezahazuj",{}}},
    {350,{"police_support",{}}},
    {351,{"play_avi_intro",{}}},
    {352,{"camera_setfov",{ARG_INT}}},
    {353,{"camera_getfov",{ARG_INT}}},
    {354,{"door_getstate",{}}},
    {355,{"car_getmaxlevels",{}}},
    {356,{"car_getactlevel",{}}},
    {357,{"car_setactlevel",{}}},
    {358,{"freeride_scoreon",{}}},
    {359,{"freeride_scoreset",{}}},
    {360,{"freeride_scoreget",{}}},
    {361,{"freeride_scoreadd",{}}},
    {362,{"taxidriver_enable",{}}},
    {363,{"human_returntotraff",{}}},
    {364,{"timer_getinterval",{}}},
    {365,{"timer_setinterval",{}}},
    {366,{"frm_getnumchildren",{}}},
    {367,{"frm_getchild",{}}},
    {368,{"human_waittoready",{}}},
    {369,{"actor_adddorici",{}}},
    {370,{"car_repair",{}}},
    {371,{"police_speed_factor",{}}},
    {372,{"cartridge_invalidate",{}}},
    {373,{"npc_shutup",{}}},
    {374,{"freeride_enablecar",{}}},
    {375,{"getcarlinenumfromtable",{}}},
    {376,{"enemy_gethostilestate",{}}},
    {377,{"human_shutup",{}}},
    {378,{"pumper_canwork",{}}},
    {379,{"group_disband",{}}},
    {380,{"inventory_clear",{}}},
    {381,{"car_disable_uo",{}}},
    {382,{"getlastsavenum",{}}},
    {383,{"freeride_traffsetup",{}}},
    {384,{"poczkurvenychbedencar",{}}},
    {385,{"human_getactanimid",{}}},
    {386,{"car_setaxis",{}}},
    {387,{"m7_zastavzkurvenepolise",{}}},
    {388,{"isvalidtaxipassenger",{}}},
    {389,{"dan_internal_1",{}}},
    {390,{"dan_internal_2",{}}},
    {4096,{"enemy_move",{}}},
    {4097,{"enemy_playanim",{}}},
    {4098,{"enemy_stopanim",{}}},
    {4099,{"enemy_lookto",{}}},
    {4100,{"enemy_wait",{}}},
    {4101,{"enemy_look",{}}},
    {4102,{"enemy_talk",{}}},
    {4103,{"enemy_stop",{}}},
    {4104,{"enemy_usecar",{}}},
    {4105,{"compareownerwith",{}}},
    {4106,{"entity_findcorner",{}}},
    {4107,{"enemy_move_to_car",{}}},
    {4108,{"enemy_car_hunt",{}}},
    {4109,{"enemy_car_escape",{}}},
    {4110,{"enemy_car_moveto",{}}},
    {4111,{"entity_bluescreen",{}}},
    {4112,{"entity_text",{}}},
    {4113,{"entity_action_move",{}}},
    {4114,{"enemy_action_follow",{}}},
    {4115,{"enemy_enter_door",{}}},
    {4116,{"enemy_action_fire",{}}},
    {4117,{"enemy_use_railway",{}}},
    {4118,{"enemy_action_runaway",{}}},
    {4119,{"enemy_action_sidelook",{}}},
    {4120,{"enemy_action_backlook",{}}},
    {4121,{"enemy_action_runcloserto",{}}},
    {4122,{"enemy_vidim",{}}},
    {4123,{"enemy_exit_railway",{}}},
    {4124,{"enemy_move_to_frame",{}}},
    {4125,{"enemy_getstate",{}}},
    {4126,{"enemy_box_goto",{}}},
    {4127,{"enemy_box_take",{}}},
    {4128,{"enemy_box_put",{}}},
    {4129,{"enemy_action_stepaway",{}}},
    {4130,{"enemy_action_strafe",{}}},
    {4131,{"enemy_action_jump",{}}},
    {4132,{"enemy_use_detector",{}}},
    {4133,{"enemy_setstate",{}}},
    {4134,{"enemy_lockstate",{}}},
    {4135,{"enemy_turnback",{}}},
    {4136,{"enemy_brainwash",{}}},
    {4137,{"enemy_kickdriver",{}}},
    {4138,{"enemy_group_new",{}}},
    {4139,{"enemy_group_add",{}}},
    {4140,{"enemy_group_del",{}}},
    {4141,{"enemy_arrest_player",{}}},
    {4142,{"enemy_naserse",{}}},
    {4143,{"enemy_actionsclear",{}}},
    {4144,{"enemy_block_checkpoint",{}}},
    {4145,{"enemy_shut_up",{}}},
    {4146,{"entity_debug_graphs",{}}},
    {4147,{"entity_action_carjump",{}}},
    {4148,{"enemy_podvadim_jak",{}}},
    {4149,{"enemy_watch",{}}},
    {4150,{"enemy_group_addcar",{}}},
    {4151,{"enemy_group_chcipni_hajzle",{}}},
    {4152,{"enemy_narohysevyser",{}}},
    {4153,{"enemy_action_phonecall",{}}},
    {4154,{"enemy_naprdelivaute",{}}},
    {4155,{"enemy_followplayer",{}}},
    {4156,{"enemy_az_po_panice_hovno",{}}},
    {4157,{"enemy_nevyhazuj",{}}},
    {4158,{"enemy_ignore_corpse",{}}},
    {4159,{"enemy_blastfire",{}}}
};

const char* getCommandName(size_t id)
{
    if(g_scriptCommandNames.count(id) > 0)
    {
        return g_scriptCommandNames[id].first;
    }
    return "UNK";
}

arg_type_t getCommandArgumentsType(size_t id)
{
    if(g_scriptCommandNames.count(id) > 0)
    {
        return g_scriptCommandNames[id].second;
    }
    static arg_type_t undefined = {};
    return undefined;
}

std::map<std::string, size_t> g_constantToID =
{
    {"UP",0},
    {"UP1",1},
    {"DOWN",2},
    {"DOWN1",3},
    {"LEFT",4},
    {"LEFT1",5},
    {"RIGHT",6},
    {"RIGHT1",7},
    {"RUN",8},
    {"RUN1",9},
    {"ACTION",10},
    {"ACTION1",11},
    {"FIRE",12},
    {"FIRE1",13},
    {"CROUCH",14},
    {"CROUCH1",15},
    {"JUMP",16},
    {"JUMP1",17},
    {"DRVUP",0},
    {"DRVUP1",1},
    {"DRVDOWN",2},
    {"DRVDOWN1",3},
    {"DRVLEFT",4},
    {"DRVLEFT1",5},
    {"DRVRIGHT",6},
    {"DRVRIGHT1",7},
    {"HANDBRAKE",41},
    {"HANDBRAKE1",42},
    {"MOTORSWITCH",57},
    {"GEARUP",45},
    {"GEARUP1",46},
    {"GEARDOWN",47},
    {"GEARDOWN1",48},
    {"HORN",49},
    {"HORN1",50},
    {"CLUTCH",55},
    {"CLUTCH1",56},
    {"INVENTORY",24},
    {"HOLSTER",25},
    {"WEAPONDROP",26},
    {"RUNSWITCH",27},
    {"RELOAD",28},
    {"SNIPERMODE",29},
    {"OBJECTIVES",30},
    {"MAP",31},
    {"SPEEDLIMIT",43},
    {"SPEEDLIMIT1",44},
};

size_t convertMafiaScriptConstantToID(const std::string constant)
{
    std::string data = constant;
    std::for_each(data.begin(), data.end(), [](char & c){
	    c = ::toupper(c);
    });
    if(g_constantToID.count(data) > 0)
    {
        return g_constantToID[data];
    }
    return -1;
}
