
#include <map>
#include <algorithm>
#include <cctype>

#include "CScript.h"

static std::map<size_t,command_t> g_scriptCommandNames =
{
    {0,{"LABEL",{ARG_STRING}}},
    {1,{"GOTO",{ARG_INT}}},
    {2,{"GOSUB",{}}},
    {3,{"RETURN",{}}},
    {4,{"WAIT",{ARG_FLT_ID_OR_FLOAT}}},
    {5,{"BEEP",{}}},
    {6,{"END",{}}},
    {7,{"DIM_FLT",{ARG_INT}}},
    {8,{"LET",{}}},
    {9,{"IF",{}}},
    {10,{"RND",{ARG_INT,ARG_INT}}},
    {11,{"DIM_FRM",{ARG_INT}}},
    {12,{"DIM_ACT",{ARG_INT}}},
    {13,{"FINDFRAME",{ARG_INT,ARG_STRING}}},
    {14,{"FRM_SETON",{ARG_INT, ARG_INT}}},
    {15,{"FRM_ISON",{ARG_INT, ARG_INT}}},
    {16,{"FRM_LINKTO",{ARG_INT, ARG_INT}}},
    {17,{"FINDACTOR",{ARG_INT, ARG_STRING}}},
    {18,{"CALL",{ARG_STRING}}},
    {19,{"IFFLTINRANGE",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {20,{"PLAYSOUND",{}}},
    {21,{"PLAYSOUNDSTOP",{ARG_INT}}},
    {22,{"PLAYSOUNDEX",{ARG_INT, ARG_INT}}},
    {23,{"STOPSOUND",{ARG_INT}}},
    {24,{"GETSOUNDTIME",{}}},
    {25,{"ACT_SETSTATE",{ARG_INT, ARG_INT}}},
    {26,{"DETECTOR_ISSIGNAL",{ARG_INT, ARG_INT, ARG_INT}}},
    {27,{"DETECTOR_SETSIGNAL",{ARG_INT, ARG_INT}}},
    {28,{"DETECTOR_INRANGE",{ARG_INT, ARG_INT}}},
    {29,{"SETCOMPASS",{ARG_INT}}},
    {30,{"SETLMLEVEL",{ARG_INT, ARG_INT}}},
    {31,{"DETECTOR_WAITFORUSE",{ARG_INT}}},
    {32,{"DETECTOR_WAITFORHIT",{}}},
    {33,{"COMMANDBLOCK",{ARG_INT}}},
    {34,{"CALLSUBROUTINE",{ARG_STRING}}},
    {35,{"SOUNDFADE",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {36,{"ENDOFMISSION",{ARG_INT, ARG_INT}}},
    {37,{"PROGRAM_STORAGE",{}}},
    {38,{"DOOR_LOCK",{ARG_INT, ARG_INT}}},
    {39,{"DOOR_OPEN",{ARG_INT, ARG_INT}}},
    {40,{"DOOR_ENABLEUS",{ARG_INT, ARG_INT}}},
    {41,{"RECCLEAR",{}}},
    {42,{"RECADDACTOR",{ARG_INT, ARG_STRING}}},
    {43,{"RECLOAD",{ARG_STRING}}},
    {44,{"RECLOADFULL",{ARG_STRING}}},
    {45,{"RECWAITFOREND",{}}},
    {46,{"RECUNLOAD",{}}},
    {47,{"LOADCOLLTREE",{}}},
    {48,{"EXPLOSION",{ARG_INT, ARG_INT}}},
    {49,{"TIMERON",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {50,{"TIMEROFF",{}}},
    {51,{"CHANGE_MISSION",{}}},
    {52,{"CAMERA_SETSWING",{ARG_INT, ARG_INT, ARG_INT}}},
    {53,{"AIRPLANE_START",{ARG_INT, ARG_INT, ARG_INT}}},
    {54,{"AIRPLANE_START2",{ARG_INT}}},
    {55,{"DEBUG_TEXT",{ARG_STRING}}},
    {56,{"GETACTORSDIST",{ARG_INT, ARG_INT, ARG_INT}}},
    {57,{"GETCARDAMAGE",{ARG_INT, ARG_INT}}},
    {58,{"HUMAN_ADDWEAPON",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {59,{"HUMAN_CANADDWEAPON",{ARG_INT, ARG_INT, ARG_INT}}},
    {60,{"HUMAN_DELWEAPON",{ARG_INT, ARG_INT}}},
    {61,{"HUMAN_ISWEAPON",{ARG_INT, ARG_INT, ARG_INT}}},
    {62,{"HUMAN_ACTIVATEWEAPON",{ARG_INT, ARG_INT}}},
    {63,{"HUMAN_ANYWEAPONINHAND",{ARG_INT, ARG_INT}}},
    {64,{"HUMAN_ANYWEAPONININVENTORY",{ARG_INT, ARG_INT}}},
    {65,{"HUMAN_GETITEMINRHAND",{ARG_INT, ARG_INT}}},
    {66,{"PRELOADMODEL",{}}},
    {67,{"LOADDIFFERENCES",{}}},
    {68,{"CLEARDIFFERENCES",{}}},
    {69,{"{",{}}},
    {70,{"}",{}}},
    {71,{"SETAIPRIORITY",{ARG_INT}}},
    {72,{"EVENT",{ARG_INT}}},
    {73,{"SETEVENT",{ARG_INT, ARG_INT, ARG_STRING}}},
    {74,{"EVENT_USE_CB",{ARG_INT}}},
    {75,{"ENEMY_CHANGEANIM",{ARG_STRING}}},
    {76,{"HUMAN_CHANGEANIM",{}}},
    {77,{"DIALOG_BEGIN",{ARG_INT, ARG_INT}}},
    {78,{"DIALOG_END",{}}},
    {79,{"DIALOG_CAMSWITCH",{ARG_INT, ARG_INT}}},
    {80,{"GAME_NIGHTMISSION",{ARG_INT}}},
    {81,{"HUMAN_LOOKTOACTOR",{ARG_INT, ARG_INT, ARG_INT}}},
    {82,{"HUMAN_LOOKTOFRAME",{}}},
    {83,{"GETMISSIONNUMBER",{ARG_INT}}},
    {84,{"SETMISSIONNUMBER",{ARG_INT}}},
    {85,{"HUMAN_LINKTOHAND",{}}},
    {86,{"HUMAN_UNLINKFROMHAND",{ARG_INT}}},
    {87,{"CREATEWEAPONFROMFRAME",{ARG_INT, ARG_INT, ARG_INT, ARG_INT}}},
    {88,{"GARAGE_ADDCAR",{ARG_INT}}},
    {89,{"GARAGE_ADDCARIDX",{}}},
    {90,{"GARAGE_DELCAR",{}}},
    {91,{"GARAGE_GENERATECARS",{}}},
    {92,{"GARAGE_RELEASECARS",{}}},
    {93,{"GARAGE_CARMANAGER",{}}},
    {94,{"PLAYER_LOCKCONTROLS",{}}},
    {95,{"PERSON_PLAYANIM",{}}},
    {96,{"PERSON_STOPANIM",{}}},
    {97,{"GUNSHOP_MENU",{}}},
    {98,{"HUMAN_SET8SLOT",{}}},
    {99,{"ENEMY_FORCESCRIPT",{}}},
    {100,{"COMPAREOWNERWITHEX",{}}},
    {101,{"HUMAN_SETPROPERTY",{}}},
    {102,{"HUMAN_GETPROPERTY",{}}},
    {103,{"DISABLECOLLS",{}}},
    {104,{"HUMAN_GETOWNER",{}}},
    {105,{"HUMAN_FORCE_SETTOCAR",{}}},
    {106,{"CAR_SETDESTROYMOTOR",{}}},
    {107,{"ACTOR_SETDIR",{}}},
    {108,{"ACTOR_SETPOS",{}}},
    {109,{"ACTOR_SETPLACEMENT",{}}},
    {110,{"GARAGE_ENABLESTEAL",{}}},
    {111,{"SETTIMEOUTEVENT",{}}},
    {112,{"EMITPARTICLE",{}}},
    {113,{"STOPPARTICLE",{}}},
    {114,{"SETPLAYERFIREEVENT",{}}},
    {115,{"FINDNEARACTOR",{}}},
    {116,{"SETPLAYERHORNEVENT",{}}},
    {117,{"HUMAN_HOLSTER",{}}},
    {118,{"CAMERA_LOCK",{ARG_INT}}},
    {119,{"CAMERA_UNLOCK",{}}},
    {120,{"SETMISSIONNAMEID",{}}},
    {121,{"WINGMAN_SETINDICATOR",{}}},
    {122,{"WINGMAN_DELINDICATOR",{}}},
    {123,{"MODEL_PLAYANIM",{ARG_INT, ARG_STRING}}},
    {124,{"MODEL_STOPANIM",{ARG_INT}}},
    {125,{"MODEL_CREATE",{ARG_INT, ARG_STRING}}},
    {126,{"MODEL_DESTROY",{ARG_INT}}},
    {127,{"HUMAN_CHANGEMODEL",{ARG_INT, ARG_STRING}}},
    {128,{"AUTOSAVEGAME",{ARG_INT}}},
    {129,{"AUTOSAVEGAMEFULL",{ARG_INT}}},
    {130,{"HUMAN_DEATH",{ARG_INT}}},
    {131,{"HUMAN_TALK",{ARG_INT, ARG_INT, ARG_INT}}},
    {132,{"HUMAN_ERASEAB",{ARG_INT}}},
    {133,{"HUMAN_CREATEAB",{ARG_INT}}},
    {134,{"POLICEMANAGER_ON",{ARG_INT, ARG_INT}}},
    {135,{"POLICEMANAGER_ADD",{ARG_STRING}}},
    {136,{"POLICEMANAGER_DEL",{ARG_STRING}}},
    {137,{"POLICEMANAGER_SETSPEED",{}}},
    {138,{"POLICEMANAGER_FORCEARREST",{}}},
    {139,{"CAR_ENABLEUS",{}}},
    {140,{"CAR_SETDOOROPEN",{}}},
    {141,{"HUMAN_SETFIRETARGET",{}}},
    {142,{"ISCARUSABLE",{}}},
    {143,{"DOOR_SETOPENPOSE",{}}},
    {144,{"AIRPLANE_ISDESTROYED",{}}},
    {145,{"HUMAN_RETURNFROMPANIC",{}}},
    {146,{"CAR_GETSPEED",{}}},
    {147,{"CAR_SETSPEED",{}}},
    {148,{"CAR_FORCESTOP",{}}},
    {149,{"CAR_BREAKMOTOR",{}}},
    {150,{"INVENTORY_PUSH",{ARG_INT}}},
    {151,{"INVENTORY_POP",{ARG_INT}}},
    {152,{"FUCKINGBOX_ADD",{ARG_INT, ARG_STRING}}},
    {153,{"FUCKINGBOX_RECOMPILE",{}}},
    {154,{"FUCKINGBOX_ADD_DEST",{ARG_INT, ARG_STRING}}},
    {155,{"HUMAN_THROWITEM",{}}},
    {156,{"FUCKINGBOX_GETNUMBOX",{ARG_INT, ARG_INT}}},
    {157,{"FUCKINGBOX_GETNUMDEST",{ARG_INT, ARG_INT}}},
    {158,{"FUCKINGBOX_MOVE",{}}},
    {159,{"WAGON_SETEVENT",{ARG_INT, ARG_INT}}},
    {160,{"WAGON_GETLASTNODE",{ARG_INT, ARG_INT}}},
    {161,{"CAR_SETSPECCOLL",{ARG_INT, ARG_INT}}},
    {162,{"CAR_GETSPECCOLL",{ARG_INT}}},
    {163,{"MISSION_OBJECTIVES",{ARG_INT}}},
    {164,{"MISSION_OBJECTIVESREMOVE",{ARG_INT}}},
    {165,{"MISSION_OBJECTIVESCLEAR",{}}},
    {166,{"RACING_MISSION6_INIT",{}}},
    {167,{"RACING_MISSION6_START",{}}},
    {168,{"CAR_EXPLOSION",{ARG_INT}}},
    {169,{"HUMAN_FROMCAR",{ARG_INT, ARG_INT}}},
    {170,{"",{}}},
    {171,{"CAR_REMOVE_DRIVER",{ARG_INT}}},
    {172,{"SETMODELTOCAR",{ARG_INT}}},
    {173,{"GETENEMYAISTATE",{}}},
    {174,{"GET_PM_STATE",{}}},
    {175,{"GET_PM_CRASHTIME",{}}},
    {176,{"GET_PM_FIRETIME",{}}},
    {177,{"GET_PM_NUMPREDATORS",{}}},
    {178,{"GET_PM_HUMANSTATE",{}}},
    {179,{"USE_LIGHTCACHE",{}}},
    {180,{"STREAM_CREATE",{ARG_INT, ARG_STRING}}},
    {181,{"STREAM_CONNECT",{}}},
    {182,{"STREAM_PLAY",{}}},
    {183,{"STREAM_PAUSE",{}}},
    {184,{"STREAM_STOP",{}}},
    {185,{"STREAM_DESTROY",{}}},
    {186,{"STREAM_FADEVOL",{}}},
    {187,{"STREAM_SETLOOP",{}}},
    {188,{"STREAM_SETPOS",{}}},
    {189,{"STREAM_GETPOS",{}}},
    {190,{"SETTANKHITCOUNT",{}}},
    {191,{"SETNOANIMHIT",{}}},
    {192,{"CARLIGHT_MAIN",{}}},
    {193,{"CARLIGHT_LIGHT",{}}},
    {194,{"CARLIGHT_INDIC_L",{}}},
    {195,{"CARLIGHT_INDIC_R",{}}},
    {196,{"CARLIGHT_INDIC_OFF",{}}},
    {197,{"CAR_MUSTSTEAL",{}}},
    {198,{"CAR_SETPROJECTOR",{}}},
    {199,{"GARAGE_CANSTEAL",{}}},
    {200,{"GARAGE_ADDLASTSTOLEN",{}}},
    {201,{"GARAGE_SHOW",{}}},
    {202,{"CAR_INWATER",{}}},
    {203,{"HUMAN_FORCEFALL",{}}},
    {204,{"CREATE_PHYSICALOBJECT",{}}},
    {205,{"DESTROY_PHYSICALOBJECT",{}}},
    {206,{"WEATHER_RESET",{}}},
    {207,{"WEATHER_SETPARAM",{}}},
    {208,{"GETTICKTIME",{ARG_INT}}},
    {209,{"GETGAMETIME",{ARG_INT}}},
    {210,{"GETACTIVEPLAYER",{}}},
    {211,{"GETANGLEACTORTOACTOR",{}}},
    {212,{"SETCITYTRAFFICVISIBLE",{}}},
    {213,{"SHOWCARDAMAGE",{}}},
    {214,{"CHARACTER_PUSH",{}}},
    {215,{"CHARACTER_POP",{}}},
    {216,{"CONSOLE_ADDTEXT",{}}},
    {217,{"CAMERA_SETRANGE",{}}},
    {218,{"ACTOR_DUPLICATE",{}}},
    {219,{"ACTOR_DELETE",{}}},
    {220,{"HUMAN_RESET",{}}},
    {221,{"HUMAN_HAVEBOX",{}}},
    {222,{"HUMAN_HAVEBODY",{}}},
    {223,{"HUMAN_STOPTALK",{}}},
    {224,{"ENEMY_BLOCK",{}}},
    {225,{"ENEMY_UNBLOCK",{}}},
    {226,{"GET_REMOTE_FLOAT",{}}},
    {227,{"GET_REMOTE_FRAME",{}}},
    {228,{"GET_REMOTE_ACTOR",{}}},
    {229,{"SET_REMOTE_FLOAT",{}}},
    {230,{"SET_REMOTE_FRAME",{}}},
    {231,{"SET_REMOTE_ACTOR",{}}},
    {232,{"GETACTORFRAME",{}}},
    {233,{"ZATMYSE",{}}},
    {234,{"CARDAMAGEVISIBLE",{}}},
    {235,{"",{}}},
    {236,{"",{}}},
    {237,{"IFPLAYERSTEALCAR",{}}},
    {238,{"INTRO_SUBTITLE_ADD",{}}},
    {239,{"SUBTITLE_ADD",{}}},
    {240,{"MATH_COS",{}}},
    {241,{"MATH_SIN",{}}},
    {242,{"MATH_ABS",{}}},
    {243,{"FRM_GETDIR",{}}},
    {244,{"FRM_SETDIR",{}}},
    {245,{"FRM_GETPOS",{}}},
    {246,{"FRM_SETPOS",{}}},
    {247,{"FRM_GETSCALE",{}}},
    {248,{"FRM_SETSCALE",{}}},
    {249,{"FRM_GETROT",{}}},
    {250,{"FRM_SETROT",{}}},
    {251,{"FRM_GETWORLDDIR",{}}},
    {252,{"FRM_GETWORLDPOS",{}}},
    {253,{"FRM_GETWORLDSCALE",{}}},
    {254,{"FRM_GETWORLDROT",{}}},
    {255,{"FRM_GETLOCALMATRIX",{}}},
    {256,{"FRM_GETWORLDMATRIX",{}}},
    {257,{"VECT_SET",{}}},
    {258,{"VECT_COPY",{}}},
    {259,{"VECT_MUL_SCL",{}}},
    {260,{"VECT_MUL_VECT",{}}},
    {261,{"VECT_MUL_QUAT",{}}},
    {262,{"VECT_MUL_MATRIX",{}}},
    {263,{"VECT_ADD_VECT",{}}},
    {264,{"VECT_SUB_VECT",{}}},
    {265,{"VECT_CROSS",{}}},
    {266,{"VECT_NORMALIZE",{}}},
    {267,{"VECT_MAGNITUDE",{}}},
    {268,{"VECT_INVERSE",{}}},
    {269,{"VECT_ANGLETO",{}}},
    {270,{"MATRIX_ZERO",{}}},
    {271,{"MATRIX_IDENTITY",{}}},
    {272,{"MATRIX_COPY",{}}},
    {273,{"MATRIX_INVERSE",{}}},
    {274,{"MATRIX_MUL",{}}},
    {275,{"QUAT_COPY",{}}},
    {276,{"QUAT_MAKE",{}}},
    {277,{"QUAT_SETDIR",{}}},
    {278,{"QUAT_EXTRACT",{}}},
    {279,{"QUAT_INVERSE",{}}},
    {280,{"QUAT_GETROTMATRIX",{}}},
    {281,{"QUAT_ADD",{}}},
    {282,{"QUAT_SUB",{}}},
    {283,{"QUAT_MUL_SCL",{}}},
    {284,{"QUAT_MUL_QUAT",{}}},
    {285,{"QUAT_DOT",{}}},
    {286,{"QUAT_NORMALIZE",{}}},
    {287,{"QUAT_ROTBYMATRIX",{}}},
    {288,{"QUAT_SLERP",{}}},
    {289,{"COLL_TESTLINE",{}}},
    {290,{"VLVP",{}}},
    {291,{"CTRL_READ",{ARG_INT,ARG_INT}}},
    {292,{"CTRL_READEX",{ARG_INT,ARG_INT}}},
    {293,{"GETFRAMEFROMACTOR",{}}},
    {294,{"ACTORUPDATEPLACEMENT",{}}},
    {295,{"RACING_AUTOINVISIBLE",{}}},
    {296,{"SETPLAYERWFALLEVENT",{}}},
    {297,{"CAR_INVISIBLE",{}}},
    {298,{"CAR_SWITCHSHOWENERGY",{}}},
    {299,{"DEBUG_GETFRAMEINFO",{}}},
    {300,{"POLICEITCHFORPLAYER",{}}},
    {301,{"NOANIMPRELOAD",{}}},
    {302,{"COMPAREACTORS",{}}},
    {303,{"SETNULLACTOR",{}}},
    {304,{"COMPAREFRAMES",{}}},
    {305,{"SETNULLFRAME",{}}},
    {306,{"SETFREERIDE",{}}},
    {307,{"ENABLEMAP",{}}},
    {308,{"FRAMEISTELEPHONE",{}}},
    {309,{"CAR_CALM",{}}},
    {310,{"BRIDGE_SHUTDOWN",{}}},
    {311,{"SETTRAFFSECTORSND",{}}},
    {312,{"CITYMUSIC_OFF",{}}},
    {313,{"CITYMUSIC_ON",{}}},
    {314,{"",{}}},
    {315,{"FRM_GETPARENT",{}}},
    {316,{"ISPOINTINSECTOR",{}}},
    {317,{"ISPOINTINAREA",{}}},
    {318,{"GETACTIVECAMERA",{}}},
    {319,{"SOUND_GETVOLUME",{}}},
    {320,{"SOUND_SETVOLUME",{}}},
    {321,{"RACING_CHANGE_MODEL",{}}},
    {322,{"CITYCACHING_TICK",{}}},
    {323,{"ACTORLIGHTNESSON",{}}},
    {324,{"CAR_LOCK",{}}},
    {325,{"CAR_LOCK_ALL",{}}},
    {326,{"PM_SHOWSYMBOL",{ARG_INT}}},
    {327,{"PM_SHOWPROGRESS",{}}},
    {328,{"PM_SETPROGRESS",{}}},
    {329,{"SETFILMMUSIC",{}}},
    {330,{"GETFILMMUSIC",{}}},
    {331,{"HUMAN_GETSEATIDX",{}}},
    {332,{"HUMAN_ENTERTOTRUCK",{}}},
    {333,{"FLOATREG_PUSH",{}}},
    {334,{"FLOATREG_POP",{}}},
    {335,{"AIRPLANESHOWDAMAGE",{}}},
    {336,{"SETNPCKILLEVENT",{}}},
    {337,{"CAR_GETSEATCOUNT",{}}},
    {338,{"FRM_SETALPHA",{}}},
    {339,{"HUMAN_THROWGRENADE",{}}},
    {340,{"DETECTOR_CREATEDYNCOLL",{}}},
    {341,{"DETECTOR_ERASEDYNCOLL",{}}},
    {342,{"CAR_UNBREAKABLE",{}}},
    {343,{"PHOBJ_IMPULS",{}}},
    {344,{"WEATHER_PREPAREBUFFER",{}}},
    {345,{"SUBTITLE",{}}},
    {346,{"HUMAN_CANDIE",{}}},
    {347,{"VERSION_IS_GERMANY",{}}},
    {348,{"VERSION_IS_EDITOR",{}}},
    {349,{"GARAGE_NEZAHAZUJ",{}}},
    {350,{"POLICE_SUPPORT",{}}},
    {351,{"PLAY_AVI_INTRO",{}}},
    {352,{"CAMERA_SETFOV",{ARG_INT}}},
    {353,{"CAMERA_GETFOV",{ARG_INT}}},
    {354,{"DOOR_GETSTATE",{}}},
    {355,{"CAR_GETMAXLEVELS",{}}},
    {356,{"CAR_GETACTLEVEL",{}}},
    {357,{"CAR_SETACTLEVEL",{}}},
    {358,{"FREERIDE_SCOREON",{}}},
    {359,{"FREERIDE_SCORESET",{}}},
    {360,{"FREERIDE_SCOREGET",{}}},
    {361,{"FREERIDE_SCOREADD",{}}},
    {362,{"TAXIDRIVER_ENABLE",{}}},
    {363,{"HUMAN_RETURNTOTRAFF",{}}},
    {364,{"TIMER_GETINTERVAL",{}}},
    {365,{"TIMER_SETINTERVAL",{}}},
    {366,{"FRM_GETNUMCHILDREN",{}}},
    {367,{"FRM_GETCHILD",{}}},
    {368,{"HUMAN_WAITTOREADY",{}}},
    {369,{"ACTOR_ADDDORICI",{}}},
    {370,{"CAR_REPAIR",{}}},
    {371,{"POLICE_SPEED_FACTOR",{}}},
    {372,{"CARTRIDGE_INVALIDATE",{}}},
    {373,{"NPC_SHUTUP",{}}},
    {374,{"FREERIDE_ENABLECAR",{}}},
    {375,{"GETCARLINENUMFROMTABLE",{}}},
    {376,{"ENEMY_GETHOSTILESTATE",{}}},
    {377,{"HUMAN_SHUTUP",{}}},
    {378,{"PUMPER_CANWORK",{}}},
    {379,{"GROUP_DISBAND",{}}},
    {380,{"INVENTORY_CLEAR",{}}},
    {381,{"CAR_DISABLE_UO",{}}},
    {382,{"GETLASTSAVENUM",{}}},
    {383,{"FREERIDE_TRAFFSETUP",{}}},
    {384,{"POCZKURVENYCHBEDENCAR",{}}},
    {385,{"HUMAN_GETACTANIMID",{}}},
    {386,{"CAR_SETAXIS",{}}},
    {387,{"M7_ZASTAVZKURVENEPOLISE",{}}},
    {388,{"ISVALIDTAXIPASSENGER",{}}},
    {389,{"DAN_INTERNAL_1",{}}},
    {390,{"DAN_INTERNAL_2",{}}},
    {4096,{"ENEMY_MOVE",{}}},
    {4097,{"ENEMY_PLAYANIM",{}}},
    {4098,{"ENEMY_STOPANIM",{}}},
    {4099,{"ENEMY_LOOKTO",{}}},
    {4100,{"ENEMY_WAIT",{}}},
    {4101,{"ENEMY_LOOK",{}}},
    {4102,{"ENEMY_TALK",{}}},
    {4103,{"ENEMY_STOP",{}}},
    {4104,{"ENEMY_USECAR",{}}},
    {4105,{"COMPAREOWNERWITH",{}}},
    {4106,{"ENTITY_FINDCORNER",{}}},
    {4107,{"ENEMY_MOVE_TO_CAR",{}}},
    {4108,{"ENEMY_CAR_HUNT",{}}},
    {4109,{"ENEMY_CAR_ESCAPE",{}}},
    {4110,{"ENEMY_CAR_MOVETO",{}}},
    {4111,{"ENTITY_BLUESCREEN",{}}},
    {4112,{"ENTITY_TEXT",{}}},
    {4113,{"ENTITY_ACTION_MOVE",{}}},
    {4114,{"ENEMY_ACTION_FOLLOW",{}}},
    {4115,{"ENEMY_ENTER_DOOR",{}}},
    {4116,{"ENEMY_ACTION_FIRE",{}}},
    {4117,{"ENEMY_USE_RAILWAY",{}}},
    {4118,{"ENEMY_ACTION_RUNAWAY",{}}},
    {4119,{"ENEMY_ACTION_SIDELOOK",{}}},
    {4120,{"ENEMY_ACTION_BACKLOOK",{}}},
    {4121,{"ENEMY_ACTION_RUNCLOSERTO",{}}},
    {4122,{"ENEMY_VIDIM",{}}},
    {4123,{"ENEMY_EXIT_RAILWAY",{}}},
    {4124,{"ENEMY_MOVE_TO_FRAME",{}}},
    {4125,{"ENEMY_GETSTATE",{}}},
    {4126,{"ENEMY_BOX_GOTO",{}}},
    {4127,{"ENEMY_BOX_TAKE",{}}},
    {4128,{"ENEMY_BOX_PUT",{}}},
    {4129,{"ENEMY_ACTION_STEPAWAY",{}}},
    {4130,{"ENEMY_ACTION_STRAFE",{}}},
    {4131,{"ENEMY_ACTION_JUMP",{}}},
    {4132,{"ENEMY_USE_DETECTOR",{}}},
    {4133,{"ENEMY_SETSTATE",{}}},
    {4134,{"ENEMY_LOCKSTATE",{}}},
    {4135,{"ENEMY_TURNBACK",{}}},
    {4136,{"ENEMY_BRAINWASH",{}}},
    {4137,{"ENEMY_KICKDRIVER",{}}},
    {4138,{"ENEMY_GROUP_NEW",{}}},
    {4139,{"ENEMY_GROUP_ADD",{}}},
    {4140,{"ENEMY_GROUP_DEL",{}}},
    {4141,{"ENEMY_ARREST_PLAYER",{}}},
    {4142,{"ENEMY_NASERSE",{}}},
    {4143,{"ENEMY_ACTIONSCLEAR",{}}},
    {4144,{"ENEMY_BLOCK_CHECKPOINT",{}}},
    {4145,{"ENEMY_SHUT_UP",{}}},
    {4146,{"ENTITY_DEBUG_GRAPHS",{}}},
    {4147,{"ENTITY_ACTION_CARJUMP",{}}},
    {4148,{"ENEMY_PODVADIM_JAK",{}}},
    {4149,{"ENEMY_WATCH",{}}},
    {4150,{"ENEMY_GROUP_ADDCAR",{}}},
    {4151,{"ENEMY_GROUP_CHCIPNI_HAJZLE",{}}},
    {4152,{"ENEMY_NAROHYSEVYSER",{}}},
    {4153,{"ENEMY_ACTION_PHONECALL",{}}},
    {4154,{"ENEMY_NAPRDELIVAUTE",{}}},
    {4155,{"ENEMY_FOLLOWPLAYER",{}}},
    {4156,{"ENEMY_AZ_PO_PANICE_HOVNO",{}}},
    {4157,{"ENEMY_NEVYHAZUJ",{}}},
    {4158,{"ENEMY_IGNORE_CORPSE",{}}},
    {4159,{"ENEMY_BLASTFIRE",{}}}
};

const char* getCommandName(size_t id)
{
    if(g_scriptCommandNames.count(id) > 0)
    {
        return g_scriptCommandNames[id].first;
    }
    return "UNK";
}

arg_type_t getCommandArgumentsType(size_t id)
{
    if(g_scriptCommandNames.count(id) > 0)
    {
        return g_scriptCommandNames[id].second;
    }
    static arg_type_t undefined = {};
    return undefined;
}

std::map<std::string, size_t> g_constantToID =
{
    {"UP",0},
    {"UP1",1},
    {"DOWN",2},
    {"DOWN1",3},
    {"LEFT",4},
    {"LEFT1",5},
    {"RIGHT",6},
    {"RIGHT1",7},
    {"RUN",8},
    {"RUN1",9},
    {"ACTION",10},
    {"ACTION1",11},
    {"FIRE",12},
    {"FIRE1",13},
    {"CROUCH",14},
    {"CROUCH1",15},
    {"JUMP",16},
    {"JUMP1",17},
    {"DRVUP",0},
    {"DRVUP1",1},
    {"DRVDOWN",2},
    {"DRVDOWN1",3},
    {"DRVLEFT",4},
    {"DRVLEFT1",5},
    {"DRVRIGHT",6},
    {"DRVRIGHT1",7},
    {"HANDBRAKE",41},
    {"HANDBRAKE1",42},
    {"MOTORSWITCH",57},
    {"GEARUP",45},
    {"GEARUP1",46},
    {"GEARDOWN",47},
    {"GEARDOWN1",48},
    {"HORN",49},
    {"HORN1",50},
    {"CLUTCH",55},
    {"CLUTCH1",56},
    {"INVENTORY",24},
    {"HOLSTER",25},
    {"WEAPONDROP",26},
    {"RUNSWITCH",27},
    {"RELOAD",28},
    {"SNIPERMODE",29},
    {"OBJECTIVES",30},
    {"MAP",31},
    {"SPEEDLIMIT",43},
    {"SPEEDLIMIT1",44},
};

size_t convertMafiaScriptConstantToID(const std::string constant)
{
    std::string data = constant;
    std::for_each(data.begin(), data.end(), [](char & c){
	    c = ::toupper(c);
    });
    if(g_constantToID.count(data) > 0)
    {
        return g_constantToID[data];
    }
    return -1;
}